# Generated by Django 4.2.7 on 2026-04-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', '点赞'), ('comment', '评论'), ('message', '私信'), ('follow', '关注'), ('new_post', '新文章')], max_length=20, verbose_name='通知类型'),
        ),
    ]
