# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment1',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments/', verbose_name='附件1'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachment2',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments/', verbose_name='附件2'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachment3',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments/', verbose_name='附件3'),
        ),
    ]
